# api_platform:
#     title: Hello API Platform
#     version: 1.0.0
#     defaults:
#         stateless: true
#         cache_headers:
#             vary: ['Content-Type', 'Authorization', 'Origin']
api_platform:
    title: 'MyDigiProjet API'
    version: '1.0.0'
    enable_entrypoint: true
    enable_docs: true
    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
    mapping:
        paths:
            - '%kernel.project_dir%/src/Entity'
    show_webby: false