api_platform:
    title: 'MyDigiProjet API'
    version: '1.0.0'
    enable_entrypoint: true
    enable_docs: true
    path_segment_name_generator: api_platform.path_segment_name_generator.underscore
    mapping:
        paths:
            - '%kernel.project_dir%/src/Entity'
            - '%kernel.project_dir%/src/Controller'
    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
    patch_formats:
        json: ['application/merge-patch+json']
    defaults:
        stateless: true
        security: 'is_granted("IS_AUTHENTICATED_FULLY")'
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    openapi:
        swagger_ui_extra_configuration:
            api_keys:
                JWT:
                    name: Authorization
                    type: header
    show_webby: false