api_platform:
    title: 'MyDigiProjet API'
    version: '1.0.0'
    enable_entrypoint: true
    enable_docs: true
    enable_swagger: true
    enable_swagger_ui: true
    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
    patch_formats:
        json: ['application/merge-patch+json']
    path_segment_name_generator: api_platform.metadata.path_segment_name_generator.underscore
    mapping:
        paths:
            - '%kernel.project_dir%/src/Entity'
            - '%kernel.project_dir%/src/Controller'
    defaults:
        stateless: true
        pagination:
            enabled: true
            items_per_page: 30
            page_parameter_name: page
            items_per_page_parameter_name: itemsPerPage