framework:
    cache:
        pools:
            cache.rate_limiter:
                adapter: cache.adapter.redis
                default_lifetime: 3600
        default_redis_provider: redis://localhost