framework:
  cache:
    default_redis_provider: 'redis://localhost:6379'
    pools:
      doctrine.system_cache_pool:
        adapter: cache.adapter.redis
      doctrine.result_cache_pool:
        adapter: cache.adapter.redis
      doctrine.second_level_cache_pool:
        adapter: cache.adapter.redis
