services:
  php:
    image: behnood147/cinespin:main
    ports:
      - "8082:80"
    volumes:
      - web:/var/www/html
    environment:
      DATABASE_URL: "mysql://app:!ChangeMe!@database:3306/app?serverVersion=8.0.32&charset=utf8mb4"
    depends_on:
      - database

  database:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: "!ChangeMe!"
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - /home/cinespin/mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  phpmyadmin-web:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-web
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - database

volumes:
  web: