parameters:
    tmdb_api_key: '%env(string:TMDB_API_KEY)%'
    tmdb_base_url: '%env(string:TMDB_BASE_URL)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $tmdbApiKey: '%env(TMDB_API_KEY)%'
            $tmdbBaseUrl: 'https://api.themoviedb.org/3'

    lexik_jwt_authentication.jwt_token_authenticator:
        class: Lexik\Bundle\JWTAuthenticationBundle\Security\Authenticator\JWTTokenAuthenticator

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\TMDBClient:
        arguments:
            $apiKey: '%tmdb_api_key%'
            $baseUrl: '%tmdb_base_url%'

    App\EventListener\JwtCreateListener:
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: onJWTCreated }

    App\OpenApi\JwtDecorator:
        decorates: api_platform.openapi.factory
        arguments: ['@App\OpenApi\JwtDecorator.inner']